---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: vbox/nginx64
    driver:
      box: nginx64
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
